language: python

sudo: required
dist: trusty

# Handle git submodules yourself
git:
    submodules: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential python3-dev xvfb python3-pyqt5.qtmultimedia
  
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

matrix:
    include:
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.5
        env: TOX_ENV=flake8

install:
  - pip install tox
  - sudo apt-get install upx git qt5-qmake qttools5-dev-tools libqt5sql5-sqlite unrar-free

script:
- tox -e ${TOX_ENV}
